name: ♥️ Bug Report
description: Report a bug in shouw.js
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug!
  - type: input
    id: version
    attributes:
      label: shouw.js version
      description: What version of shouw.js are you using?
      placeholder: e.g. v1.0.0
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction steps
      description: |
        Please provide detailed steps to reproduce the bug.
        This could include:
          - Code snippets
          - Specific commands run
          - Relevant configuration files
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      description: What actually happened?
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output.
      render: bash
  - type: textarea
    id: suggested-fix
    attributes:
      label: Suggested fix
      description: If you have a suggested fix, please provide it here.